const navItems = [
  ['dashboard','◫','Visão geral'],['clients','♙','Clientes'],['projects','◇','Projetos'],['processes','⇢','Processos'],
  ['tasks','✓','Tarefas'],['agenda','◷','Agenda'],['commercial','◎','Comercial'],['products','▦','Produtos e serviços'],['installations','⌂','Acompanhamento'],['operations','⚒','Operação'],['finance','＄','Financeiro'],
  ['bi','▥','Business Intelligence'],
  ['equipment','▣','Equipamentos'],['knowledge','▤','Conhecimento']
];

const seed = {
  catalogVersion:2,
  clients:[
    {id:'cli-1',name:'Condomínio Horizonte',document:'12.345.678/0001-90',contact:'Marina Alves',email:'marina@horizonte.com.br',phone:'(11) 98820-1142',address:'Av. das Nações, 1500',city:'São Paulo',notes:'Atendimento pela portaria administrativa.',status:'Ativo'},
    {id:'cli-2',name:'Grupo Atlântico',document:'23.456.789/0001-12',contact:'Ricardo Nunes',email:'ricardo@atlantico.com.br',phone:'(11) 97741-8890',address:'Rua do Porto, 240',city:'Santos',notes:'Acesso técnico mediante agendamento.',status:'Ativo'},
    {id:'cli-3',name:'Clínica Veredas',document:'34.567.890/0001-34',contact:'Camila Rocha',email:'camila@veredas.com.br',phone:'(19) 99812-3410',address:'Av. Brasil, 820',city:'Campinas',notes:'Intervenções fora do horário de atendimento.',status:'Ativo'}],
  projects:[
    {id:'prj-1',code:'PRJ-026',name:'Controle de acesso — Torre A',clientId:'cli-1',manager:'Marcos',technicalStage:'Instalação',status:'Em execução',progress:68,due:'22 ago',budget:78500,cost:49120},
    {id:'prj-2',code:'PRJ-027',name:'CFTV e rede administrativa',clientId:'cli-2',manager:'Fernanda',technicalStage:'Projeto técnico',status:'Planejamento',progress:24,due:'3 set',budget:124000,cost:18600},
    {id:'prj-3',code:'PRJ-024',name:'Automação de portões',clientId:'cli-3',manager:'Marcos',technicalStage:'Cabeamento',status:'Bloqueado',progress:81,due:'18 ago',budget:46200,cost:39800}],
  quotes:[
    {id:'orc-1',clientId:'cli-1',title:'Controle de acesso Torre A',value:78500,status:'Aprovado'},
    {id:'orc-2',clientId:'cli-2',title:'CFTV administrativo',value:124000,status:'Em negociação'},
    {id:'orc-3',clientId:'cli-3',title:'Aditivo automação',value:12600,status:'Aguardando cliente'}],
  opportunities:[],
  products:[
    {id:'prd-unifi-gateway',sku:'UNIFI-GATEWAY',name:'Gateway UniFi — modelo a definir',brand:'UniFi',category:'Rede',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-unifi-switch',sku:'UNIFI-SW-POE',name:'Switch PoE UniFi — modelo a definir',brand:'UniFi',category:'Rede',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-unifi-ap',sku:'UNIFI-AP',name:'Access Point UniFi — modelo a definir',brand:'UniFi',category:'Rede Wi-Fi',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-unifi-camera',sku:'UNIFI-CAMERA',name:'Câmera UniFi Protect — modelo a definir',brand:'UniFi',category:'Câmeras',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-unifi-nvr',sku:'UNIFI-NVR',name:'Gravador UniFi Protect — modelo a definir',brand:'UniFi',category:'Câmeras',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-embrace-controller',sku:'EMBRACE-CTRL',name:'Controlador Scenario Embrace',brand:'Scenario Embrace',category:'Automação',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-embrace-light',sku:'EMBRACE-LUZ',name:'Módulo de iluminação Scenario Embrace',brand:'Scenario Embrace',category:'Automação',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-embrace-interface',sku:'EMBRACE-INT',name:'Interface de automação Scenario Embrace',brand:'Scenario Embrace',category:'Automação',mode:'Venda ou disponibilização',unit:'un',cost:0,price:0,active:true},
    {id:'prd-denon-receiver',sku:'DENON-AVR',name:'Receiver Denon — modelo a definir',brand:'Denon',category:'Áudio e vídeo',mode:'Venda',unit:'un',cost:0,price:0,active:true},
    {id:'prd-stage-speaker',sku:'STAGE-CAIXA',name:'Caixa acústica STAGE — modelo a definir',brand:'STAGE',category:'Áudio',mode:'Venda',unit:'un',cost:0,price:0,active:true},
    {id:'prd-morel-speaker',sku:'MOREL-CAIXA',name:'Caixa acústica Morel — modelo a definir',brand:'Morel',category:'Áudio',mode:'Venda',unit:'un',cost:0,price:0,active:true},
    {id:'prd-bw-speaker',sku:'BW-CAIXA',name:'Caixa acústica B&W — modelo a definir',brand:'B&W',category:'Áudio',mode:'Venda',unit:'un',cost:0,price:0,active:true}],
  quoteRooms:[
    {id:'amb-1',quoteId:'orc-1',name:'Portaria principal',items:[]},
    {id:'amb-2',quoteId:'orc-1',name:'Acesso garagem',items:[]},
    {id:'amb-3',quoteId:'orc-1',name:'Sala técnica',items:[]},
    {id:'amb-4',quoteId:'orc-2',name:'Recepção',items:[]}],
  tasks:[
    {id:'tsk-1',title:'Confirmar entrega dos controladores',projectId:'prj-1',assignee:'Fernanda',priority:'Urgente',status:'Aberta',due:'Hoje'},
    {id:'tsk-2',title:'Revisar diagrama de rede',projectId:'prj-2',assignee:'Marcos',priority:'Alta',status:'Em andamento',due:'Amanhã'},
    {id:'tsk-3',title:'Retornar aprovação do aditivo',projectId:'prj-3',assignee:'Paulo',priority:'Urgente',status:'Bloqueada',due:'Atrasada'},
    {id:'tsk-4',title:'Separar ferramentas para visita',projectId:'prj-1',assignee:'Lucas',priority:'Média',status:'Aberta',due:'19 ago'}],
  equipment:[
    {id:'eq-1',name:'Controladora AC-400',brand:'Intelbras',serial:'AC4-82931',location:'Condomínio Horizonte',status:'Instalado'},
    {id:'eq-2',name:'Câmera VIP 3240',brand:'Intelbras',serial:'VIP-19022',location:'Estoque',status:'Disponível'},
    {id:'eq-3',name:'Switch PoE 24 portas',brand:'Ubiquiti',serial:'USW-73810',location:'Grupo Atlântico',status:'Instalado'}],
  installations:[
    {id:'ins-1',clientId:'cli-1',projectId:'prj-1',site:'Torre A · Portaria',type:'Controle de acesso',lead:'Marcos',stage:'Instalação',progress:68,due:'22 ago',status:'Em execução'},
    {id:'ins-2',clientId:'cli-2',projectId:'prj-2',site:'Sede administrativa',type:'CFTV e rede',lead:'Fernanda',stage:'Planejamento',progress:24,due:'3 set',status:'Planejamento'},
    {id:'ins-3',clientId:'cli-3',projectId:'prj-3',site:'Unidade Campinas',type:'Automação de portões',lead:'Marcos',stage:'Aguardando cliente',progress:81,due:'18 ago',status:'Bloqueado'}],
  activities:[
    {id:'act-1',clientId:'cli-1',date:'14 ago · 15:40',type:'Visita técnica',title:'Vistoria da infraestrutura concluída',note:'Pontos da Torre A conferidos e registrados por Marcos.'},
    {id:'act-2',clientId:'cli-1',date:'12 ago · 09:15',type:'Contato',title:'Cliente confirmou janela de instalação',note:'Acesso liberado para a equipe das 08h às 17h.'},
    {id:'act-3',clientId:'cli-2',date:'13 ago · 11:20',type:'Proposta',title:'Versão 2 do orçamento enviada',note:'Incluído switch PoE adicional solicitado pelo cliente.'},
    {id:'act-4',clientId:'cli-3',date:'10 ago · 16:00',type:'Pendência',title:'Aditivo aguardando aprovação',note:'Execução pausada até retorno do responsável financeiro.'}],
  articles:[
    {id:'kb-1',tag:'Procedimento',title:'Checklist de entrega técnica',summary:'Validações obrigatórias antes do aceite e encerramento de um projeto.'},
    {id:'kb-2',tag:'Solução',title:'Diagnóstico de falha em controladoras',summary:'Passo a passo para isolar alimentação, rede, firmware e comunicação.'},
    {id:'kb-3',tag:'Manual',title:'Padrão de identificação de cabos',summary:'Convenções de etiquetas, racks, pontos e documentação fotográfica.'}]
};

const initialCalendarDate=new Date();
const state = { view:'dashboard', query:'', selectedClient:null, selectedQuote:null, biDimension:'client', agendaYear:initialCalendarDate.getFullYear(), agendaMonth:initialCalendarDate.getMonth(), data:loadData(), revision:0, updatedAt:null, syncing:false };
const $ = s => document.querySelector(s);
const money = v => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v);
const clientName = id => state.data.clients.find(c=>c.id===id)?.name || 'Sem cliente';
const projectName = id => state.data.projects.find(p=>p.id===id)?.name || 'Sem projeto';
const productById = id => state.data.products.find(p=>p.id===id);
const roomTotals = room => room.items.reduce((t,item)=>{const p=productById(item.productId);if(p){t.cost+=p.cost*item.qty;t.price+=p.price*item.qty}return t},{cost:0,price:0});
const uid = prefix => `${prefix}-${Date.now().toString(36)}`;
function loadData(){try{const saved=JSON.parse(localStorage.getItem('proelium-data'));if(!saved)return structuredClone(seed);const resetCatalog=saved.catalogVersion!==seed.catalogVersion;const merged={...structuredClone(seed),...saved,catalogVersion:seed.catalogVersion,installations:saved.installations||structuredClone(seed.installations),activities:saved.activities||structuredClone(seed.activities),quotes:saved.quotes||structuredClone(seed.quotes),opportunities:saved.opportunities||[],products:resetCatalog?structuredClone(seed.products):(saved.products||structuredClone(seed.products)),quoteRooms:resetCatalog?(saved.quoteRooms||structuredClone(seed.quoteRooms)).map(r=>({...r,items:[]})):(saved.quoteRooms||structuredClone(seed.quoteRooms))};merged.clients=merged.clients.map(c=>({...c,document:c.document||'',email:c.email||'',address:c.address||'',notes:c.notes||''}));merged.projects=merged.projects.map(p=>({...p,technicalStage:p.technicalStage||'Projeto técnico'}));return merged}catch{return structuredClone(seed)}}
async function persist(){
  localStorage.setItem('proelium-data',JSON.stringify(state.data));
  if(location.protocol==='file:')return;
  if(state.syncing){toast('Aguarde a sincronização terminar e tente novamente.');return}
  state.syncing=true;
  try{
    const response=await fetch('./api/data',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:state.data,baseRevision:state.revision})});
    const payload=await response.json();
    if(response.status===409){await refreshSharedData(true);toast('Outro aparelho alterou os dados. A tela foi atualizada; repita sua última ação.');return}
    if(!response.ok)throw new Error(payload.error||'Falha ao salvar');
    state.revision=Number(payload.revision||state.revision||0);
    state.updatedAt=payload.updatedAt||state.updatedAt;
    document.body.dataset.shared='true';
  }catch{toast('Servidor indisponível: a alteração ainda não foi compartilhada.')}finally{state.syncing=false}
}
function normalizeSharedData(shared){const saved=shared||structuredClone(seed),resetCatalog=saved.catalogVersion!==seed.catalogVersion;const merged={...structuredClone(seed),...saved,catalogVersion:seed.catalogVersion,installations:saved.installations||[],activities:saved.activities||[],quotes:saved.quotes||[],opportunities:saved.opportunities||[],products:resetCatalog?structuredClone(seed.products):(saved.products||[]),quoteRooms:resetCatalog?(saved.quoteRooms||[]).map(r=>({...r,items:[]})):(saved.quoteRooms||[])};merged.clients=(merged.clients||[]).map(c=>({...c,document:c.document||'',email:c.email||'',address:c.address||'',notes:c.notes||''}));merged.projects=(merged.projects||[]).map(p=>({...p,technicalStage:p.technicalStage||'Projeto técnico'}));return merged}
async function refreshSharedData(force=false){
  const response=await fetch('./api/data',{cache:'no-store'});
  if(!response.ok)throw new Error('Servidor indisponível');
  const payload=await response.json();
  const remoteRevision=Number(payload.revision||0);
  const changedByRevision=remoteRevision>state.revision;
  const changedByDate=Boolean(payload.updatedAt&&payload.updatedAt!==state.updatedAt);
  if(payload.data&&(force||changedByRevision||changedByDate)){
    state.data=normalizeSharedData(payload.data);
    state.revision=remoteRevision;
    state.updatedAt=payload.updatedAt||null;
    localStorage.setItem('proelium-data',JSON.stringify(state.data));
    render();
  }else{
    state.revision=remoteRevision;
    state.updatedAt=payload.updatedAt||state.updatedAt;
  }
  document.body.dataset.shared='true';
  return payload;
}
async function connectSharedData(){
  if(location.protocol==='file:')return;
  try{
    const payload=await refreshSharedData(true);
    if(!payload.data)await persist();
    const events=new EventSource('./api/events');
    events.addEventListener('data-updated',async event=>{
      const update=JSON.parse(event.data);
      if(Number(update.revision)>state.revision&&!state.syncing){
        try{await refreshSharedData();toast('Dados atualizados por outro aparelho.')}catch{}
      }
    });
    events.onerror=()=>{document.body.dataset.shared='reconnecting'};
    events.onopen=()=>{document.body.dataset.shared='true'};
    setInterval(()=>refreshSharedData().catch(()=>{}),5000);
    document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshSharedData().catch(()=>{})});
  }catch{toast('Modo local: dados ainda não estão compartilhados.')}
}
function badge(value){const low=value.toLowerCase();const color=low.includes('bloq')||low.includes('atras')||low.includes('urg')?'red':low.includes('exec')||low.includes('andamento')||low.includes('instal')?'blue':low.includes('plane')||low.includes('alta')?'amber':'green';return `<span class="badge ${color}">${value}</span>`}
function matches(...values){return values.join(' ').toLowerCase().includes(state.query.toLowerCase())}

function renderNav(){ $('#navigation').innerHTML=navItems.map(([id,icon,label])=>`<button class="nav-item ${state.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join(''); }
function heading(title,subtitle,action){const label=action==='opportunity'?'Nova oportunidade':'Novo registro';return `<div class="section-heading"><div><h2>${title}</h2><p>${subtitle}</p></div>${action?`<button class="button primary" data-add="${action}">+ ${label}</button>`:''}</div>`}
function table(headers,rows){return `<div class="card table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`}

function dashboard(){
  const active=state.data.projects.filter(p=>p.status!=='Concluído').length, blocked=state.data.projects.filter(p=>p.status==='Bloqueado').length;
  const overdue=state.data.tasks.filter(t=>t.due==='Atrasada').length, approved=state.data.projects.reduce((s,p)=>s+p.budget,0), cost=state.data.projects.reduce((s,p)=>s+p.cost,0);
  const projects=state.data.projects.slice(0,4).map(p=>`<tr><td><div class="entity">${p.name}</div><div class="subtext">${p.code} · ${clientName(p.clientId)}</div></td><td>${badge(p.status)}</td><td><strong>${p.progress}%</strong><div class="progress"><span style="width:${p.progress}%"></span></div></td><td>${p.due}</td></tr>`).join('');
  const attention=state.data.tasks.filter(t=>t.priority==='Urgente'||t.due==='Atrasada').map(t=>`<div class="attention-item"><span class="attention-dot ${t.due==='Atrasada'?'red':''}"></span><div><strong>${t.title}</strong><p>${projectName(t.projectId)} · ${t.assignee}</p></div><time>${t.due}</time></div>`).join('');
  return `<div class="kpi-grid"><div class="kpi"><div class="kpi-top"><span>Projetos ativos</span><span class="kpi-icon">◇</span></div><div class="kpi-value">${active}</div><div class="kpi-note ${blocked?'attention':''}">${blocked} bloqueado${blocked===1?'':'s'}</div></div><div class="kpi"><div class="kpi-top"><span>Tarefas abertas</span><span class="kpi-icon">✓</span></div><div class="kpi-value">${state.data.tasks.length}</div><div class="kpi-note attention">${overdue} em atraso</div></div><div class="kpi"><div class="kpi-top"><span>Carteira aprovada</span><span class="kpi-icon">＄</span></div><div class="kpi-value">${money(approved)}</div><div class="kpi-note">Projetos cadastrados</div></div><div class="kpi"><div class="kpi-top"><span>Margem estimada</span><span class="kpi-icon">↗</span></div><div class="kpi-value">${approved?Math.round((approved-cost)/approved*100):0}%</div><div class="kpi-note">${money(approved-cost)} projetados</div></div></div><div class="dashboard-grid"><div class="card"><div class="card-head"><h3>Projetos em andamento</h3><button data-view="projects">Ver todos →</button></div><div class="table-wrap"><table><thead><tr><th>Projeto</th><th>Status</th><th>Progresso</th><th>Prazo</th></tr></thead><tbody>${projects}</tbody></table></div></div><div class="card"><div class="card-head"><h3>Precisa de atenção</h3><button data-view="tasks">Abrir tarefas →</button></div><div class="attention-list">${attention||'<div class="empty">Tudo em ordem.</div>'}</div></div></div>`;
}
function clients(){const rows=state.data.clients.filter(c=>matches(c.name,c.contact,c.city)).map(c=>{const installs=state.data.installations.filter(i=>i.clientId===c.id);const open=state.data.tasks.filter(t=>state.data.projects.find(p=>p.id===t.projectId)?.clientId===c.id&&t.status!=='Concluída').length;return `<tr class="clickable-row" data-client="${c.id}"><td><div class="entity">${c.name}</div><div class="subtext">${c.id}</div></td><td>${c.contact}</td><td>${c.phone}</td><td>${c.city}</td><td>${installs.length}</td><td>${open}</td><td>${badge(c.status)}</td><td>→</td></tr>`});return heading('CRM de clientes','Ficha completa, histórico e instalações de cada cliente.','client')+table(['Cliente','Contato principal','Telefone','Cidade','Instalações','Pendências','Status',''],rows)}
function clientDetail(){
  const c=state.data.clients.find(x=>x.id===state.selectedClient);if(!c){state.view='clients';return clients()}
  const projects=state.data.projects.filter(p=>p.clientId===c.id), quotes=state.data.quotes.filter(q=>q.clientId===c.id), installs=state.data.installations.filter(i=>i.clientId===c.id), acts=state.data.activities.filter(a=>a.clientId===c.id), equipment=state.data.equipment.filter(e=>e.location.includes(c.name.split(' ')[0]));
  return `<button class="back-link" data-view="clients">← Voltar para clientes</button><div class="client-hero card"><div><p class="eyebrow">FICHA DO CLIENTE</p><h2>${c.name}</h2><p>${c.document||'Documento não informado'} · ${c.city} · ${badge(c.status)}</p></div><div class="hero-actions"><button class="button secondary" data-edit-client="${c.id}">Editar cadastro</button><button class="button secondary" data-add="activity">+ Contato</button><button class="button primary" data-add="installation">+ Instalação</button></div></div><div class="crm-flow">${['Contatos','Orçamentos','Projetos','Acompanhamento'].map((s,i)=>`<div><span>${i+1}</span><strong>${s}</strong><small>${[acts.length,quotes.length,projects.length,state.data.tasks.filter(t=>projects.some(p=>p.id===t.projectId)).length][i]} registros</small></div>`).join('')}</div><div class="client-summary"><div class="card info-card"><span>Contato principal</span><strong>${c.contact}</strong><p>${c.phone}<br>${c.email||'E-mail não informado'}</p></div><div class="card info-card"><span>Endereço</span><strong>${c.city}</strong><p>${c.address||'Endereço não informado'}</p></div><div class="card info-card"><span>Orçamentos</span><strong>${quotes.length}</strong><p>${money(quotes.reduce((s,q)=>s+q.value,0))} apresentados</p></div><div class="card info-card"><span>Projetos</span><strong>${projects.length}</strong><p>${equipment.length} equipamentos vinculados</p></div></div>${c.notes?`<div class="client-notes"><strong>Observações:</strong> ${c.notes}</div>`:''}<div class="technical-flow card"><div><span>1</span><strong>Projeto técnico</strong><small>Levantamento e desenho</small></div><div><span>2</span><strong>Cabeamento</strong><small>Infraestrutura e pontos</small></div><div><span>3</span><strong>Instalação</strong><small>Equipamentos, testes e entrega</small></div></div><div class="client-layout"><div class="card"><div class="card-head"><h3>Projetos e execução</h3><button data-view="projects">Ver projetos →</button></div><div class="installation-list">${projects.map(p=>`<div class="install-card"><div><span class="install-code">${p.code}</span><strong>${p.name}</strong><p>Responsável: ${p.manager} · Prazo: ${p.due}</p></div><div class="install-status">${badge(p.technicalStage)}<strong>${p.progress}%</strong></div><div class="progress wide"><span style="width:${p.progress}%"></span></div><small>Etapa técnica: ${p.technicalStage}</small></div>`).join('')||'<div class="empty">Nenhum projeto cadastrado.</div>'}</div></div><div class="card"><div class="card-head"><h3>Histórico e acompanhamento</h3><button data-add="activity">+ Registrar</button></div><div class="timeline">${acts.map(a=>`<div class="timeline-item"><span></span><div><time>${a.date} · ${a.type}</time><strong>${a.title}</strong><p>${a.note}</p></div></div>`).join('')||'<div class="empty">Sem histórico.</div>'}</div></div></div>`
}
function projects(){const rows=state.data.projects.filter(p=>matches(p.name,p.code,clientName(p.clientId),p.manager,p.technicalStage)).map(p=>`<tr><td><div class="entity">${p.name}</div><div class="subtext">${p.code}</div></td><td><button class="link-button" data-client="${p.clientId}">${clientName(p.clientId)}</button></td><td>${badge(p.technicalStage)}</td><td>${badge(p.status)}</td><td>${p.manager}</td><td><strong>${p.progress}%</strong><div class="progress"><span style="width:${p.progress}%"></span></div></td><td>${money(p.budget)}</td></tr>`);return heading('Projetos','Três etapas: projeto técnico, cabeamento e instalação.','project')+`<div class="technical-flow compact card"><div><span>1</span><strong>Projeto técnico</strong></div><div><span>2</span><strong>Cabeamento</strong></div><div><span>3</span><strong>Instalação</strong></div></div>`+table(['Projeto','Cliente','Etapa técnica','Status','Responsável','Progresso','Valor'],rows)}
function tasks(){const rows=state.data.tasks.filter(t=>matches(t.title,projectName(t.projectId),t.assignee,t.status)).map(t=>`<tr><td><div class="entity">${t.title}</div><div class="subtext">${projectName(t.projectId)}</div></td><td>${t.assignee}</td><td>${badge(t.priority)}</td><td>${badge(t.status)}</td><td>${t.due}${t.time?` · ${t.time}`:''}</td></tr>`);return heading('Tarefas e pendências','Tudo que possui responsável, prioridade e prazo.','task')+table(['Tarefa','Responsável','Prioridade','Status','Prazo'],rows)}
function calendarDate(value){if(!value)return null;const now=new Date();if(value==='Hoje')return new Date(now.getFullYear(),now.getMonth(),now.getDate());if(value==='Amanhã')return new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);if(/^\d{4}-\d{2}-\d{2}$/.test(value)){const [year,month,day]=value.split('-').map(Number);return new Date(year,month-1,day)}const match=String(value).match(/(\d{1,2})\s*(jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez)/i);if(!match)return null;const months={jan:0,fev:1,mar:2,abr:3,mai:4,jun:5,jul:6,ago:7,set:8,out:9,nov:10,dez:11};return new Date(now.getFullYear(),months[match[2].toLowerCase()],Number(match[1]))}
function agenda(){const entries=[...state.data.tasks.map(t=>({type:'Tarefa',title:t.title,detail:projectName(t.projectId),person:t.assignee,when:t.due||'',time:t.time||'',status:t.status})),...state.data.installations.map(i=>({type:'Instalação',title:i.type,detail:`${clientName(i.clientId)} · ${i.site}`,person:i.lead,when:i.due||'',time:'',status:i.status})),...state.data.opportunities.filter(o=>!['Ganho','Perdido'].includes(o.stage)&&o.nextAction).map(o=>({type:'Comercial',title:o.nextAction,detail:`${o.company} · ${o.stage}`,person:o.owner,when:o.nextDue||'',time:'',status:o.stage}))].map(e=>({...e,date:calendarDate(e.when)}));const filtered=entries.filter(e=>matches(e.title,e.detail,e.person,e.when,e.type));const year=state.agendaYear,month=state.agendaMonth,firstDay=new Date(year,month,1),start=(firstDay.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=Array.from({length:42},(_,index)=>{const day=index-start+1;return day>0&&day<=days?day:null}),monthName=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(firstDay),eventsForDay=day=>filtered.filter(e=>e.date&&e.date.getFullYear()===year&&e.date.getMonth()===month&&e.date.getDate()===day),unscheduled=filtered.filter(e=>!e.date);return heading('Agenda operacional','Planeje o mês reunindo Comercial, Tarefas e Acompanhamento.','task')+`<div class="agenda-toolbar"><button class="button secondary" data-agenda-month="prev">←</button><strong>${monthName}</strong><button class="button secondary" data-agenda-month="next">→</button></div><div class="calendar-weekdays">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=>`<span>${d}</span>`).join('')}</div><div class="month-grid">${cells.map(day=>{if(!day)return '<div class="month-cell muted-cell"></div>';const events=eventsForDay(day),visible=events.slice(0,3);return `<section class="month-cell"><header><span>${day}</span><small>${events.length||''}</small></header>${visible.map(e=>`<div class="calendar-event ${e.type==='Instalação'?'instalacao':e.type==='Comercial'?'comercial':'tarefa'}"><b>${e.time?`${e.time} `:''}${e.title}</b><small>${e.type} · ${e.person}</small></div>`).join('')}${events.length>3?`<small class="more-events">+${events.length-3} compromisso(s)</small>`:''}</section>`}).join('')}</div>${unscheduled.length?`<section class="card unscheduled"><div class="card-head"><h3>Sem data definida</h3><span>${unscheduled.length}</span></div>${unscheduled.map(e=>`<div><strong>${e.title}</strong><small>${e.type} · ${e.detail} · ${e.person}</small></div>`).join('')}</section>`:''}`}
function commercial(){
  const stages=['Novo contato','Qualificação','Visita','Orçamento'];
  const active=state.data.opportunities.filter(o=>!['Ganho','Perdido'].includes(o.stage));
  const filtered=active.filter(o=>matches(o.company,o.contact,o.source,o.owner,o.stage,o.nextAction));
  const won=state.data.opportunities.filter(o=>o.stage==='Ganho').length;
  const lost=state.data.opportunities.filter(o=>o.stage==='Perdido').length;
  const quoteRows=state.data.quotes.filter(q=>matches(q.title,clientName(q.clientId),q.status)).map(q=>{const rooms=state.data.quoteRooms.filter(r=>r.quoteId===q.id),total=rooms.reduce((s,r)=>s+roomTotals(r).price,0);return `<tr class="clickable-row" data-quote="${q.id}"><td><div class="entity">${q.title}</div><div class="subtext">${q.id}</div></td><td>${clientName(q.clientId)}</td><td>${rooms.length}</td><td>${money(total||q.value)}</td><td>${badge(q.status)}</td><td>→</td></tr>`});
  return heading('Comercial e contatos','Acompanhe oportunidades desde o primeiro contato até o orçamento.','opportunity')+`<div class="kpi-grid"><div class="kpi"><div class="kpi-top">Oportunidades abertas</div><div class="kpi-value">${active.length}</div><div class="kpi-note">em atendimento</div></div><div class="kpi"><div class="kpi-top">Próximas ações</div><div class="kpi-value">${active.filter(o=>o.nextAction).length}</div><div class="kpi-note">a acompanhar</div></div><div class="kpi"><div class="kpi-top">Ganhas</div><div class="kpi-value">${won}</div><div class="kpi-note">convertidas em cliente</div></div><div class="kpi"><div class="kpi-top">Perdidas</div><div class="kpi-value">${lost}</div><div class="kpi-note">com motivo registrado</div></div></div><div class="pipeline">${stages.map(stage=>{const deals=filtered.filter(o=>o.stage===stage);return `<section class="stage"><div class="stage-head"><span>${stage}</span><span class="stage-count">${deals.length}</span></div>${deals.map(o=>`<article class="deal"><strong>${o.company}</strong><p>${o.contact} · ${o.source}</p><p><b>Próxima:</b> ${o.nextAction||'Não definida'}${o.nextDue?` · ${o.nextDue}`:''}</p><div class="deal-value">${o.estimatedValue?money(o.estimatedValue):'Valor a definir'}</div><div class="deal-actions"><button class="link-button" data-advance-opportunity="${o.id}">Avançar</button><button class="link-button" data-convert-opportunity="${o.id}">Converter em cliente</button></div></article>`).join('')||'<p class="subtext">Nenhuma oportunidade.</p>'}</section>`}).join('')}</div><section class="card commercial-history"><div class="card-head"><h3>Oportunidades concluídas</h3></div>${table(['Oportunidade','Resultado','Responsável','Motivo'],state.data.opportunities.filter(o=>['Ganho','Perdido'].includes(o.stage)).map(o=>`<tr><td><div class="entity">${o.company}</div><div class="subtext">${o.contact}</div></td><td>${badge(o.stage)}</td><td>${o.owner}</td><td>${o.lossReason||'—'}</td></tr>`))}</section><section class="card commercial-history"><div class="card-head"><h3>Orçamentos por ambiente</h3></div>${table(['Orçamento','Cliente','Ambientes','Valor estimado','Status',''],quoteRows)}</section>`
}
function products(){const rows=state.data.products.filter(p=>matches(p.sku,p.name,p.brand,p.category,p.mode)).map(p=>`<tr><td><div class="entity">${p.name}</div><div class="subtext">${p.sku} · ${p.brand||'Sem marca'}</div></td><td>${p.category}</td><td>${badge(p.mode)}</td><td>${p.unit}</td><td>${p.cost?money(p.cost):'A definir'}</td><td>${p.price?money(p.price):'A definir'}</td><td>${p.price?Math.round((p.price-p.cost)/p.price*100)+'%':'—'}</td><td><button class="delete-icon" data-delete-product="${p.id}" aria-label="Excluir ${p.name}" title="Excluir produto">×</button></td></tr>`);return heading('Banco de produtos e serviços','Linhas UniFi, Scenario Embrace, Denon, STAGE, Morel e B&W.','product')+table(['Produto / serviço','Categoria','Modalidade','Unidade','Custo','Preço','Margem',''],rows)}
function quoteDetail(){
  const quote=state.data.quotes.find(q=>q.id===state.selectedQuote);if(!quote){state.view='commercial';return commercial()}const rooms=state.data.quoteRooms.filter(r=>r.quoteId===quote.id),totals=rooms.reduce((t,r)=>{const x=roomTotals(r);t.cost+=x.cost;t.price+=x.price;return t},{cost:0,price:0}),margin=totals.price?Math.round((totals.price-totals.cost)/totals.price*100):0,max=Math.max(1,...rooms.map(r=>roomTotals(r).price));
  return `<button class="back-link" data-view="commercial">← Voltar para orçamentos</button>${heading(quote.title,`${clientName(quote.clientId)} · ${quote.id}`)}<div class="quote-actions"><button class="button secondary" data-add="room">+ Adicionar cômodo</button><button class="button primary" data-add="quoteItem">+ Adicionar item</button></div><div class="kpi-grid"><div class="kpi"><div class="kpi-top">Ambientes</div><div class="kpi-value">${rooms.length}</div><div class="kpi-note">Análise individual</div></div><div class="kpi"><div class="kpi-top">Preço de venda</div><div class="kpi-value">${money(totals.price)}</div><div class="kpi-note">Soma de todos os cômodos</div></div><div class="kpi"><div class="kpi-top">Custo previsto</div><div class="kpi-value">${money(totals.cost)}</div><div class="kpi-note">Produtos e serviços</div></div><div class="kpi"><div class="kpi-top">Margem bruta</div><div class="kpi-value">${margin}%</div><div class="kpi-note">${money(totals.price-totals.cost)} projetados</div></div></div><div class="quote-analysis card"><div class="card-head"><h3>Comparação estratégica dos ambientes</h3></div><div class="room-bars">${rooms.map(r=>{const t=roomTotals(r);return `<div class="room-bar"><strong>${r.name}</strong><div class="bi-track"><span style="width:${t.price/max*100}%"></span></div><span>${money(t.price)}</span><small>${t.price?Math.round((t.price-t.cost)/t.price*100):0}% margem</small></div>`}).join('')}</div></div><div class="room-grid">${rooms.map(r=>{const t=roomTotals(r);return `<section class="card room-card"><div class="card-head"><div><h3>${r.name}</h3><small>${r.items.length} itens · ${money(t.price)}</small></div><strong>${t.price?Math.round((t.price-t.cost)/t.price*100):0}% margem</strong></div><div class="table-wrap"><table><thead><tr><th>Item</th><th>Qtd.</th><th>Custo</th><th>Venda</th><th>Total</th></tr></thead><tbody>${r.items.map(item=>{const p=productById(item.productId);return p?`<tr><td><div class="entity">${p.name}</div><div class="subtext">${p.mode}</div></td><td>${item.qty} ${p.unit}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td>${money(p.price*item.qty)}</td></tr>`:''}).join('')}</tbody></table></div><footer><span>Custo: ${money(t.cost)}</span><strong>Resultado: ${money(t.price-t.cost)}</strong></footer></section>`}).join('')||'<div class="empty">Adicione o primeiro cômodo para começar.</div>'}</div>`
}
function installations(){const rows=state.data.installations.filter(i=>matches(clientName(i.clientId),i.type,i.site,i.lead,i.stage,i.status)).map(i=>`<tr><td><div class="entity">${i.type}</div><div class="subtext">${i.site}</div></td><td><button class="link-button" data-client="${i.clientId}">${clientName(i.clientId)}</button></td><td>${i.lead}</td><td>${i.stage}</td><td><strong>${i.progress}%</strong><div class="progress"><span style="width:${i.progress}%"></span></div></td><td>${i.due}</td><td>${badge(i.status)}</td></tr>`);return heading('Acompanhamento','Controle da execução e histórico após a aprovação.','installation')+`<div class="stage-strip">${['Projeto técnico','Cabeamento','Instalação'].map((s,i)=>`<div><span>${i+1}</span><strong>${s}</strong></div>`).join('')}</div>`+table(['Instalação','Cliente','Responsável','Etapa atual','Progresso','Prazo','Status'],rows)}
function processes(){const stages=['Entrada e qualificação','Visita e levantamento','Orçamento e aprovação','Planejamento e compras','Execução','Testes e entrega','Pós-venda'];return heading('Processos','Fluxo operacional padrão, reutilizado em cada projeto.')+`<div class="card attention-list">${stages.map((s,i)=>`<div class="attention-item"><span class="badge green">${i+1}</span><div><strong>${s}</strong><p>${i===0?'Dados mínimos do cliente e da demanda':i===6?'Garantia, manutenção e histórico':'Checklist, responsável e condição de conclusão'}</p></div><time>${i<2?'Comercial':'Operação'}</time></div>`).join('')}</div>`}
function operations(){return heading('Operação','Agenda, ordens de serviço e execução em campo.')+table(['Ordem','Projeto','Equipe','Agenda','Status'],[`<tr><td><div class="entity">OS-1048</div></td><td>${state.data.projects[0]?.name||'-'}</td><td>Marcos + Lucas</td><td>18 ago · 08:00</td><td>${badge('Agendada')}</td></tr>`,`<tr><td><div class="entity">OS-1047</div></td><td>${state.data.projects[2]?.name||'-'}</td><td>Lucas</td><td>14 ago · 13:30</td><td>${badge('Bloqueada')}</td></tr>`])}
function finance(){const approved=state.data.projects.reduce((s,p)=>s+p.budget,0),cost=state.data.projects.reduce((s,p)=>s+p.cost,0);const rows=state.data.projects.map(p=>`<tr><td><div class="entity">${p.name}</div></td><td>${money(p.budget)}</td><td>${money(p.cost)}</td><td>${money(p.budget-p.cost)}</td><td>${p.budget?Math.round((p.budget-p.cost)/p.budget*100):0}%</td></tr>`);return `<div class="kpi-grid"><div class="kpi"><div class="kpi-top">Receita aprovada</div><div class="kpi-value">${money(approved)}</div></div><div class="kpi"><div class="kpi-top">Custo realizado</div><div class="kpi-value">${money(cost)}</div></div><div class="kpi"><div class="kpi-top">Resultado projetado</div><div class="kpi-value">${money(approved-cost)}</div></div></div>`+heading('Financeiro por projeto','Visão gerencial; não substitui contabilidade.')+table(['Projeto','Aprovado','Custo','Resultado','Margem'],rows)}
function bi(){
  const approved=state.data.projects.reduce((s,p)=>s+p.budget,0), cost=state.data.projects.reduce((s,p)=>s+p.cost,0), avg=state.data.projects.length?approved/state.data.projects.length:0;
  const key=state.biDimension, groups={};state.data.projects.forEach(p=>{const label=key==='client'?clientName(p.clientId):key==='stage'?p.technicalStage:p.manager;groups[label]??={label,budget:0,cost:0,count:0,progress:0};groups[label].budget+=p.budget;groups[label].cost+=p.cost;groups[label].count++;groups[label].progress+=p.progress});
  const items=Object.values(groups).sort((a,b)=>b.budget-a.budget), max=Math.max(1,...items.map(i=>i.budget));
  return heading('Business Intelligence','Cruze informações comerciais, operacionais e financeiras.')+`<div class="bi-toolbar card"><label>Visualizar por<select id="biDimension"><option value="client" ${key==='client'?'selected':''}>Cliente</option><option value="stage" ${key==='stage'?'selected':''}>Etapa técnica</option><option value="manager" ${key==='manager'?'selected':''}>Responsável</option></select></label><span>Fonte: todos os registros cadastrados</span></div><div class="kpi-grid"><div class="kpi"><div class="kpi-top">Clientes</div><div class="kpi-value">${state.data.clients.length}</div><div class="kpi-note">${state.data.activities.length} interações registradas</div></div><div class="kpi"><div class="kpi-top">Orçamentos</div><div class="kpi-value">${money(state.data.quotes.reduce((s,q)=>s+q.value,0))}</div><div class="kpi-note">${state.data.quotes.length} propostas</div></div><div class="kpi"><div class="kpi-top">Ticket médio de projeto</div><div class="kpi-value">${money(avg)}</div><div class="kpi-note">${state.data.projects.length} projetos</div></div><div class="kpi"><div class="kpi-top">Margem projetada</div><div class="kpi-value">${approved?Math.round((approved-cost)/approved*100):0}%</div><div class="kpi-note">${money(approved-cost)} de resultado</div></div></div><div class="dashboard-grid"><div class="card"><div class="card-head"><h3>Valor aprovado por ${key==='client'?'cliente':key==='stage'?'etapa':'responsável'}</h3></div><div class="bi-bars">${items.map(i=>`<div class="bi-bar-row"><div><strong>${i.label}</strong><small>${i.count} projeto${i.count===1?'':'s'}</small></div><div class="bi-track"><span style="width:${i.budget/max*100}%"></span></div><b>${money(i.budget)}</b></div>`).join('')}</div></div><div class="card"><div class="card-head"><h3>Eficiência e execução</h3></div><div class="bi-breakdown">${items.map(i=>{const margin=i.budget?Math.round((i.budget-i.cost)/i.budget*100):0,progress=Math.round(i.progress/i.count);return `<div><div><strong>${i.label}</strong><small>Progresso médio ${progress}%</small></div><span>${margin}% margem</span></div>`}).join('')}</div></div></div><div class="card bi-table"><div class="card-head"><h3>Base cruzada para análise</h3></div>${table(['Cliente','Projeto','Etapa','Responsável','Aprovado','Custo','Margem','Progresso'],state.data.projects.map(p=>`<tr><td>${clientName(p.clientId)}</td><td>${p.name}</td><td>${p.technicalStage}</td><td>${p.manager}</td><td>${money(p.budget)}</td><td>${money(p.cost)}</td><td>${p.budget?Math.round((p.budget-p.cost)/p.budget*100):0}%</td><td>${p.progress}%</td></tr>`)).replace('class="card table-wrap"','class="table-wrap"')}</div>`
}
function equipment(){const rows=state.data.equipment.filter(e=>matches(e.name,e.brand,e.serial,e.location)).map(e=>`<tr><td><div class="entity">${e.name}</div><div class="subtext">${e.brand}</div></td><td>${e.serial}</td><td>${e.location}</td><td>${badge(e.status)}</td></tr>`);return heading('Equipamentos','Estoque, instalação, garantia e manutenção.')+table(['Equipamento','Número de série','Local','Status'],rows)}
function knowledge(){const cards=state.data.articles.filter(a=>matches(a.title,a.tag,a.summary)).map(a=>`<article class="card article"><span class="tag">${a.tag}</span><h3>${a.title}</h3><p>${a.summary}</p><button class="button secondary">Abrir artigo</button></article>`).join('');return heading('Base de conhecimento','Procedimentos, manuais e soluções reutilizáveis.')+`<div class="knowledge-grid">${cards||'<div class="empty">Nenhum artigo encontrado.</div>'}</div>`}
const views={dashboard,clients,clientDetail,projects,processes,tasks,agenda,commercial,quoteDetail,products,installations,operations,finance,bi,equipment,knowledge};

function render(){renderNav();$('#pageTitle').textContent=state.view==='clientDetail'?'Cliente 360°':state.view==='quoteDetail'?'Análise do orçamento':navItems.find(n=>n[0]===state.view)[2];$('#content').innerHTML=views[state.view]();if(state.view==='clientDetail')addDeleteControl();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openForm(b.dataset.add));document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>openClient(b.dataset.client));document.querySelectorAll('[data-quote]').forEach(b=>b.onclick=()=>openQuote(b.dataset.quote));document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>openForm('client',b.dataset.editClient));document.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct));document.querySelectorAll('[data-advance-opportunity]').forEach(b=>b.onclick=()=>advanceOpportunity(b.dataset.advanceOpportunity));document.querySelectorAll('[data-convert-opportunity]').forEach(b=>b.onclick=()=>convertOpportunity(b.dataset.convertOpportunity));document.querySelectorAll('[data-agenda-month]').forEach(b=>b.onclick=()=>{state.agendaMonth+=b.dataset.agendaMonth==='next'?1:-1;if(state.agendaMonth>11){state.agendaMonth=0;state.agendaYear++}if(state.agendaMonth<0){state.agendaMonth=11;state.agendaYear--}render()});const dim=$('#biDimension');if(dim)dim.onchange=e=>{state.biDimension=e.target.value;render()}}
function go(view){state.view=view;state.query='';$('#globalSearch').value='';$('#sidebar').classList.remove('open');render()}
function openClient(id){state.selectedClient=id;state.view='clientDetail';render()}
function openQuote(id){state.selectedQuote=id;state.view='quoteDetail';render()}
function addDeleteControl(){const actions=document.querySelector('.client-hero .hero-actions');if(!actions)return;const button=document.createElement('button');button.className='button danger-outline';button.textContent='Excluir cliente';button.onclick=()=>deleteClient(state.selectedClient);actions.prepend(button)}
function deleteClient(id){const client=state.data.clients.find(c=>c.id===id);if(!client)return;const projectIds=state.data.projects.filter(p=>p.clientId===id).map(p=>p.id),quoteIds=state.data.quotes.filter(q=>q.clientId===id).map(q=>q.id);if(!confirm(`Excluir ${client.name}?\n\nTambém serão removidos os projetos, tarefas, orçamentos, instalações e todo o histórico vinculados. Esta ação não pode ser desfeita.`))return;state.data.tasks=state.data.tasks.filter(t=>!projectIds.includes(t.projectId));state.data.installations=state.data.installations.filter(i=>i.clientId!==id);state.data.activities=state.data.activities.filter(a=>a.clientId!==id);state.data.projects=state.data.projects.filter(p=>p.clientId!==id);state.data.quoteRooms=state.data.quoteRooms.filter(r=>!quoteIds.includes(r.quoteId));state.data.quotes=state.data.quotes.filter(q=>q.clientId!==id);state.data.clients=state.data.clients.filter(c=>c.id!==id);state.selectedClient=null;state.view='clients';persist();render();toast('Cliente e registros vinculados foram excluídos.')}
function deleteProduct(id){const product=productById(id);if(!product)return;const uses=state.data.quoteRooms.reduce((n,r)=>n+r.items.filter(i=>i.productId===id).length,0);const detail=uses?`\n\nEste produto aparece em ${uses} ambiente(s) de orçamento e também será removido desses ambientes.`:'';if(!confirm(`Excluir ${product.name}?${detail}\n\nEsta ação não pode ser desfeita.`))return;state.data.products=state.data.products.filter(p=>p.id!==id);state.data.quoteRooms.forEach(r=>r.items=r.items.filter(i=>i.productId!==id));persist();render();toast('Produto excluído do catálogo.')}
function advanceOpportunity(id){const opportunity=state.data.opportunities.find(o=>o.id===id);if(!opportunity)return;const stages=['Novo contato','Qualificação','Visita','Orçamento'];const index=stages.indexOf(opportunity.stage);opportunity.stage=stages[Math.min(index+1,stages.length-1)];persist();render();toast(`Oportunidade movida para ${opportunity.stage}.`)}
function convertOpportunity(id){const opportunity=state.data.opportunities.find(o=>o.id===id);if(!opportunity)return;const existing=state.data.clients.find(c=>c.name.toLowerCase()===opportunity.company.toLowerCase());if(!existing){state.data.clients.push({id:uid('cli'),name:opportunity.company,document:'',contact:opportunity.contact,email:opportunity.email,phone:opportunity.phone,address:'',city:'',notes:`Origem: oportunidade comercial (${opportunity.source}).`,status:'Potencial'})}opportunity.stage='Ganho';opportunity.lossReason='';persist();render();toast(existing?'Oportunidade marcada como ganha.':'Cliente criado a partir da oportunidade.')}

const forms={
  client:{title:'Cliente',fields:[['name','Nome / razão social','text'],['document','CNPJ / CPF','text'],['contact','Contato principal','text'],['email','E-mail','email'],['phone','Telefone','tel'],['city','Cidade','text'],['address','Endereço completo','text'],['status','Status','clientStatus'],['notes','Observações','textarea']]},
  opportunity:{title:'Nova oportunidade',fields:[['company','Empresa / pessoa','text'],['contact','Contato','text'],['phone','Telefone','tel'],['email','E-mail','email'],['source','Origem do contato','text'],['owner','Responsável pelo atendimento','text'],['stage','Etapa atual','opportunityStage'],['nextAction','Próxima ação','text'],['nextDue','Prazo da próxima ação','text'],['estimatedValue','Valor estimado (R$)','number'],['lossReason','Motivo de perda (se perdido)','text']]},
  project:{title:'Novo projeto',fields:[['name','Nome do projeto','text'],['code','Código','text'],['clientId','Cliente','clients'],['manager','Responsável','text'],['technicalStage','Etapa técnica','technicalStage'],['budget','Valor aprovado (R$)','number'],['due','Prazo','text']]},
  task:{title:'Nova tarefa',fields:[['title','Título','text'],['projectId','Projeto','projects'],['assignee','Responsável','text'],['priority','Prioridade','priority'],['due','Data','date'],['time','Horário','time']]},
  installation:{title:'Nova instalação',fields:[['clientId','Cliente','clients'],['projectId','Projeto','projects'],['type','Tipo da instalação','text'],['site','Local / unidade','text'],['lead','Responsável técnico','text'],['due','Prazo','text']]},
  activity:{title:'Registrar no histórico',fields:[['clientId','Cliente','clients'],['type','Tipo do registro','activityType'],['title','Assunto','text'],['note','Descrição completa','textarea']]}
  ,product:{title:'Novo produto ou serviço',fields:[['sku','Código / SKU','text'],['name','Nome do item','text'],['brand','Marca / linha','text'],['category','Categoria','text'],['mode','Modalidade','productMode'],['unit','Unidade','unit'],['cost','Custo unitário (R$)','number'],['price','Preço de venda (R$)','number']]}
  ,room:{title:'Novo cômodo / ambiente',fields:[['name','Nome do cômodo ou ambiente','text']]}
  ,quoteItem:{title:'Adicionar item ao ambiente',fields:[['roomId','Cômodo / ambiente','rooms'],['productId','Produto ou serviço','products'],['qty','Quantidade','number']]}
};
function openForm(kind,editId=''){const def=forms[kind],current=editId?state.data.clients.find(c=>c.id===editId):null;$('#dialogTitle').textContent=current?'Atualizar cliente':def.title;$('#recordForm').dataset.kind=kind;$('#recordForm').dataset.editId=editId;$('#saveButton').textContent=current?'Atualizar cadastro':'Salvar registro';$('#formFields').innerHTML=def.fields.map(([name,label,type])=>{let input;const value=current?.[name]??(state.selectedClient&&name==='clientId'?state.selectedClient:'');const options=(values)=>values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('');if(type==='clients')input=`<select name="${name}" required>${state.data.clients.map(c=>`<option value="${c.id}" ${c.id===value?'selected':''}>${c.name}</option>`)}</select>`;else if(type==='projects')input=`<select name="${name}" required>${state.data.projects.map(p=>`<option value="${p.id}">${p.name}</option>`)}</select>`;else if(type==='products')input=`<select name="${name}" required>${state.data.products.map(p=>`<option value="${p.id}">${p.name} · ${money(p.price)}</option>`)}</select>`;else if(type==='rooms'){const rooms=state.data.quoteRooms.filter(r=>r.quoteId===state.selectedQuote);input=`<select name="${name}" required>${rooms.map(r=>`<option value="${r.id}">${r.name}</option>`)}</select>`}else if(type==='priority')input=`<select name="${name}">${options(['Média','Alta','Urgente','Baixa'])}</select>`;else if(type==='technicalStage')input=`<select name="${name}">${options(['Projeto técnico','Cabeamento','Instalação'])}</select>`;else if(type==='opportunityStage')input=`<select name="${name}">${options(['Novo contato','Qualificação','Visita','Orçamento','Ganho','Perdido'])}</select>`;else if(type==='clientStatus')input=`<select name="${name}">${options(['Ativo','Potencial','Inativo'])}</select>`;else if(type==='productMode')input=`<select name="${name}">${options(['Venda','Disponibilização','Venda ou disponibilização','Serviço'])}</select>`;else if(type==='unit')input=`<select name="${name}">${options(['un','m','h','kit','mês'])}</select>`;else if(type==='activityType')input=`<select name="${name}">${options(['Contato','Visita técnica','Proposta','Pendência','Manutenção'])}</select>`;else if(type==='textarea')input=`<textarea name="${name}" required>${value}</textarea>`;else input=`<input name="${name}" type="${type}" value="${value}" min="${type==='number'?'0':''}" step="${type==='number'?'0.01':''}" required>`;return `<div class="field ${type==='textarea'||name==='address'?'full':''}"><label>${label}</label>${input}</div>`}).join('');$('#recordDialog').showModal()}
function saveRecord(kind,data,editId=''){if(kind==='client'){if(editId){const index=state.data.clients.findIndex(c=>c.id===editId);state.data.clients[index]={...state.data.clients[index],...data}}else state.data.clients.push({id:uid('cli'),...data})}if(kind==='opportunity')state.data.opportunities.unshift({id:uid('opp'),company:data.company,contact:data.contact,phone:data.phone,email:data.email,source:data.source,owner:data.owner,stage:data.stage,nextAction:data.nextAction,nextDue:data.nextDue,estimatedValue:Number(data.estimatedValue||0),lossReason:data.lossReason});if(kind==='project')state.data.projects.push({id:uid('prj'),name:data.name,code:data.code,clientId:data.clientId,manager:data.manager,technicalStage:data.technicalStage,budget:Number(data.budget||0),cost:0,status:'Planejamento',progress:0,due:data.due});if(kind==='task')state.data.tasks.push({id:uid('tsk'),title:data.title,projectId:data.projectId,assignee:data.assignee,priority:data.priority,status:'Aberta',due:data.due,time:data.time});if(kind==='installation')state.data.installations.push({id:uid('ins'),clientId:data.clientId,projectId:data.projectId,type:data.type,site:data.site,lead:data.lead,stage:'Projeto técnico',progress:0,due:data.due,status:'Planejamento'});if(kind==='activity')state.data.activities.unshift({id:uid('act'),clientId:data.clientId,type:data.type,title:data.title,note:data.note,date:'Agora'});if(kind==='product')state.data.products.push({id:uid('prd'),sku:data.sku,name:data.name,brand:data.brand,category:data.category,mode:data.mode,unit:data.unit,cost:Number(data.cost),price:Number(data.price),active:true});if(kind==='room')state.data.quoteRooms.push({id:uid('amb'),quoteId:state.selectedQuote,name:data.name,items:[]});if(kind==='quoteItem'){const room=state.data.quoteRooms.find(r=>r.id===data.roomId);const existing=room?.items.find(i=>i.productId===data.productId);if(existing)existing.qty+=Number(data.qty);else room?.items.push({productId:data.productId,qty:Number(data.qty)})}persist();render();toast(editId?'Cadastro atualizado com sucesso.':'Registro salvo com sucesso.')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}

$('#navigation').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)go(b.dataset.view)});
$('#globalSearch').addEventListener('input',e=>{state.query=e.target.value;render()});
$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
$('#recordForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));saveRecord(e.currentTarget.dataset.kind,data,e.currentTarget.dataset.editId);$('#recordDialog').close();e.currentTarget.reset();e.currentTarget.dataset.editId='';$('#saveButton').textContent='Salvar registro'});
render();
connectSharedData();
