'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ModuleLayout } from '../components/ModuleLayout';
import { apiGet, apiPut } from '../../lib/api';

type Profile = Record<string, unknown>;
export default function SettingsPage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { apiGet<{ company?: Profile }>('/api/company/profile').then((payload) => setProfile(payload.company || null)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Falha ao carregar empresa.')); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await apiPut<{ company?: Profile }>('/api/company/profile', { name: values.name, responsible: values.responsible, phone: values.phone, profileInfo: values.profileInfo }); setProfile(result.company || { ...profile, ...values }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar a empresa.'); } finally { setSaving(false); } }
  return <ModuleLayout eyebrow="CONFIGURAÇÕES" title="Empresa" description="Identidade e situação da empresa autenticada.">{error && <p className="error">{error}</p>}{profile && <form className="profile" onSubmit={save}><label>Nome<input name="name" defaultValue={String(profile.name || '')} required /></label><label>Responsável<input name="responsible" defaultValue={String(profile.responsible || '')} required /></label><label>Telefone<input name="phone" defaultValue={String(profile.phone || '')} /></label><label>Informações<textarea name="profileInfo" defaultValue={String(profile.profileInfo || '')} rows={4} /></label><p className="status">Status: {String(profile.status || 'Não informado')} · Licença: {String(profile.licenseStatus || 'Não informado')}</p><button disabled={saving}>{saving ? 'Salvando…' : 'Salvar alterações'}</button></form>}{!error && !profile && <p>Empresa não disponível para esta sessão.</p>}<style jsx>{`.profile{display:grid;gap:14px;margin-top:28px;padding:24px;border-radius:12px;background:var(--proelium-card);box-shadow:0 5px 20px #26282812}.profile label{display:grid;gap:6px;font-size:12px;font-weight:700}.profile input,.profile textarea{padding:11px;border:1px solid var(--proelium-line);border-radius:7px;font:inherit}.status{font-size:12px;color:var(--proelium-muted)}.profile button{border:0;border-radius:7px;padding:11px;background:var(--proelium-orange);color:#fff;font-weight:700;cursor:pointer}.profile button:disabled{opacity:.6}`}</style></ModuleLayout>;
}
